<?php

namespace Database\Seeders;

use App\Models\Tour;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TourSeeder extends Seeder
{
    public function run(): void
    {
        $tours = [
            [
                'name' => 'Passeio pela Baía de Luanda',
                'short_description' => 'Descubra a majestosa Baía de Luanda com uma embarcação privada, admirando o skyline e os pôr-do-sol mais belos de Angola.',
                'description' => "A Baía de Luanda é um dos pontos mais icónicos da capital angolana. Neste tour marítimo exclusivo, você embarcará numa embarcação confortável e percorrerá as águas cristalinas da baía, com vistas panorâmicas para a Ilha de Luanda e o moderno skyline da cidade.\n\nInclui paragem na Ilha do Cabo para um almoço de peixe fresco num restaurante local selecionado. O guia local partilhará histórias fascinantes sobre a história marítima de Luanda e a sua importância como porto colonial.\n\nO tour ocorre ao final da tarde para coincidir com o pôr-do-sol, momento verdadeiramente inesquecível.",
                'city' => 'Luanda',
                'province' => 'Luanda',
                'location' => 'Cais do porto de Luanda, Ilha',
                'price' => 25000.00,
                'duration_days' => 1,
                'max_participants' => 20,
                'available_spots' => 18,
                'category' => 'natureza',
                'difficulty' => 'facil',
                'is_active' => true,
                'is_featured' => true,
                'highlights' => ['Baía panorâmica de Luanda', 'Pôr-do-sol inesquecível', 'Peixe fresco na Ilha', 'Guia local experiente'],
                'includes' => ['Transporte marítimo', 'Almoço de peixe fresco', 'Guia bilíngue (PT/EN)', 'Seguro de viagem'],
                'excludes' => ['Bebidas alcoólicas', 'Gorjetas', 'Despesas pessoais'],
            ],
            [
                'name' => 'Tour Cultural pelo Museu Nacional da Escravatura',
                'short_description' => 'Uma jornada histórica pela memória da escravatura em Angola, visitando o icónico museu e a Árvore do Esquecimento.',
                'description' => "O Museu Nacional da Escravatura, situado em Luanda, é um dos museus mais importantes de África no que concerne à história da escravatura. Este tour cultural de meio dia guia-o através de exposições que documentam o período colonial e o tráfico negreiro.\n\nA visita inclui a famosa Árvore do Esquecimento e a Árvore da Memória, símbolos poderosos desta época histórica. O guia especializado contextualiza os artefactos e documentos históricos de forma sensível e informativa.\n\nIdeal para estudantes, historiadores e qualquer pessoa interessada na história de Angola e do continente africano.",
                'city' => 'Luanda',
                'province' => 'Luanda',
                'location' => 'Bairro da Miramar, Luanda',
                'price' => 8500.00,
                'duration_days' => 1,
                'max_participants' => 15,
                'available_spots' => 12,
                'category' => 'historico',
                'difficulty' => 'facil',
                'is_active' => true,
                'is_featured' => false,
                'highlights' => ['Museu da Escravatura', 'Árvore do Esquecimento', 'Exposições históricas únicas', 'Guia historiador credenciado'],
                'includes' => ['Entrada no museu', 'Guia especializado', 'Material didático'],
                'excludes' => ['Transporte próprio', 'Refeições', 'Fotografias profissionais'],
            ],
            [
                'name' => 'Cataratas de Calandula - Aventura no Malanje',
                'short_description' => 'As maiores cataratas de Angola e umas das mais imponentes de África. Uma experiência natural de tirar o fôlego.',
                'description' => "As Cataratas de Calandula (antiga Duque de Bragança) são as maiores cataratas de Angola com 105 metros de altura e 410 metros de largura. Localizadas no Rio Lucala, na província do Malanje, formam um dos espectáculos naturais mais impressionantes do continente africano.\n\nEste tour de 2 dias inclui transporte de Luanda até Malanje, pernoita em pousada local e visita guiada às cataratas. Será possível fazer trilhos nos arredores das cataratas, nadar em poças naturais e visitar a comunidade local próxima.\n\nO segundo dia inclui visita aos Pedras Negras de Pungo-Andongo, formações rochosas misteriosas carregadas de lendas Mbundu.",
                'city' => 'Malanje',
                'province' => 'Malanje',
                'location' => 'Calandula, Rio Lucala',
                'price' => 85000.00,
                'duration_days' => 2,
                'max_participants' => 12,
                'available_spots' => 10,
                'category' => 'aventura',
                'difficulty' => 'moderado',
                'is_active' => true,
                'is_featured' => true,
                'highlights' => ['Cataratas de 105m de altura', 'Pedras Negras de Pungo-Andongo', 'Mergulho em poças naturais', 'Cultura Mbundu'],
                'includes' => ['Transporte ida e volta de Luanda', 'Alojamento 1 noite', 'Pequeno-almoço e jantar', 'Guia de montanha', 'Seguro de aventura'],
                'excludes' => ['Almoços', 'Equipamento pessoal de trekking', 'Gorjetas'],
            ],
            [
                'name' => 'Praias Paradisíacas de Benguela',
                'short_description' => 'Explore as melhores praias do litoral de Benguela, com areias brancas e águas quentes do Atlântico Sul.',
                'description' => "Benguela é conhecida pelas suas praias de areia branca e clima ameno. Este tour de 1 dia percorre as mais belas praias da cidade, incluindo a Praia Morena, Praia do Lobito e as extensas areias de Baía Farta.\n\nO itinerário inclui uma paragem para mergulho com snorkel nos recifes costeiros, observação de fauna marinha e um almoço de frutos do mar frescos num restaurante tradicional com vista para o mar.\n\nÀ tarde, visita ao Palácio do Governador e ao centro histórico de Benguela, uma das cidades coloniais mais bem preservadas de Angola.",
                'city' => 'Benguela',
                'province' => 'Benguela',
                'location' => 'Praça do Município, Benguela',
                'price' => 45000.00,
                'duration_days' => 1,
                'max_participants' => 16,
                'available_spots' => 14,
                'category' => 'praia',
                'difficulty' => 'facil',
                'is_active' => true,
                'is_featured' => true,
                'highlights' => ['Praias de areia branca', 'Snorkel nos recifes', 'Frutos do mar frescos', 'Centro histórico colonial'],
                'includes' => ['Transporte local', 'Equipamento de snorkel', 'Almoço de frutos do mar', 'Guia local bilingue'],
                'excludes' => ['Despesas pessoais', 'Gorjetas', 'Bebidas além da água'],
            ],
            [
                'name' => 'Parque Nacional da Kissama - Safari Africano',
                'short_description' => 'Safari de 2 dias no maior parque nacional de Angola, observando elefantes, bófalos, palancas e muito mais.',
                'description' => "O Parque Nacional da Kissama, a apenas 70 km de Luanda, é o maior parque nacional de Angola com 9.960 km². Este safari de 2 dias é uma oportunidade única de observar a rica fauna angolana em plena natureza.\n\nO parque abriga elefantes-africanos, bófalos, palancas-negras (símbolo nacional de Angola), zebras, gnus e diversas espécies de aves. Os guias rangers especializados garantem uma experiência segura e enriquecedora.\n\nO alojamento é em eco-lodge dentro do parque, para uma imersão total na natureza. Safari de manhã e ao entardecer, períodos de maior actividade animal. Inclui visita às margens do Rio Kwanza.",
                'city' => 'Luanda',
                'province' => 'Bengo',
                'location' => 'Porta de entrada do PN Kissama, Km 70 Estrada Luanda-Porto Amboim',
                'price' => 120000.00,
                'duration_days' => 2,
                'max_participants' => 8,
                'available_spots' => 6,
                'category' => 'safari',
                'difficulty' => 'facil',
                'is_active' => true,
                'is_featured' => true,
                'highlights' => ['Elefantes e palancas-negras', 'Safari ao nascer do sol', 'Eco-lodge dentro do parque', 'Rio Kwanza'],
                'includes' => ['2 safaris guiados', 'Alojamento em eco-lodge', 'Todas as refeições', 'Transporte de Luanda', 'Ranger especializado'],
                'excludes' => ['Bebidas alcoólicas', 'Gorjetas', 'Seguro pessoal'],
            ],
            [
                'name' => 'Trekking na Serra da Leba e Lubango',
                'short_description' => 'Percorra uma das estradas mais bonitas de África com vista para o deserto do Namibe e explore a cidade serrana do Lubango.',
                'description' => "A Serra da Leba, no Lubango, oferece uma das paisagens mais dramáticas de Angola. A estrada que serpenteia a escarpa da serra, com vista para o deserto do Namibe, é considerada uma das mais belas de África.\n\nO tour de 3 dias inclui trekking na escarpa da serra, visita ao Cristo Rei do Lubango (réplica do Cristo Redentor), tour pelo centro histórico do Lubango e excursão ao Deserto do Namibe para observação de plantas Welwitschia, endémicas do deserto do Namibe e com mais de 1.000 anos de idade.\n\nAlojamento em pension familiar no Lubango, com gastronomia local típica.",
                'city' => 'Lubango',
                'province' => 'Huíla',
                'location' => 'Miradouro da Serra da Leba, Lubango',
                'price' => 95000.00,
                'duration_days' => 3,
                'max_participants' => 10,
                'available_spots' => 8,
                'category' => 'aventura',
                'difficulty' => 'moderado',
                'is_active' => true,
                'is_featured' => false,
                'highlights' => ['Vista panorâmica Serra da Leba', 'Cristo Rei do Lubango', 'Deserto do Namibe', 'Plantas Welwitschia milenares'],
                'includes' => ['Transporte aéreo Luanda-Lubango', 'Alojamento 2 noites', 'Guia de montanha', 'Pequenos-almoços'],
                'excludes' => ['Almoços e jantares (exceto day 1)', 'Equipamento pessoal', 'Gorjetas'],
            ],
            [
                'name' => 'Gastronomia Traditional Luandense',
                'short_description' => 'Uma visita às cozinhas tradicionais de Luanda, mercados locais e restaurantes típicos para provar o melhor da culinária angolana.',
                'description' => "Angola tem uma culinária rica e variada, com influências africanas, portuguesas e brasileiras. Este tour gastronómico de 1 dia leva-o pelos sabores autênticos de Luanda.\n\nO dia começa no Mercado do Roque Santeiro, o maior mercado de África, onde poderá observar e comprar especiarias, produtos frescos e artefactos locais. Em seguida, workshop de culinária tradicional angolana com chef local, aprendendo a preparar Muamba de Galinha, Calulu de Peixe e Kissanga.\n\nAlmoço nos restaurantes mais autênticos do Bairro Rangel. À tarde, visita a bares tradicionais onde poderá provar a cerveja caseira (chibukari) e snacks típicos.",
                'city' => 'Luanda',
                'province' => 'Luanda',
                'location' => 'Mercado do Roque Santeiro, Luanda',
                'price' => 32000.00,
                'duration_days' => 1,
                'max_participants' => 12,
                'available_spots' => 10,
                'category' => 'gastronomia',
                'difficulty' => 'facil',
                'is_active' => true,
                'is_featured' => false,
                'highlights' => ['Mercado do Roque Santeiro', 'Workshop de culinária angolana', 'Muamba de Galinha do autêntico', 'Mercados tradicionais'],
                'includes' => ['Transporte', 'Workshop de culinária', 'Almoço tradicional completo', 'Ingredientes do workshop', 'Guia gastronómico'],
                'excludes' => ['Compras pessoais no mercado', 'Bebidas fora da degustação', 'Gorjetas'],
            ],
            [
                'name' => 'Fortaleza de São Miguel e Cidade Alta',
                'short_description' => 'Explore a história colonial de Luanda visitando a icónica Fortaleza de São Miguel e o centro histórico da Cidade Alta.',
                'description' => "A Fortaleza de São Miguel, construída em 1576, é o edifício mais antigo de Luanda e símbolo da fundação da cidade. Este tour histórico de meio dia percorre os pontos mais emblemáticos do centro histórico de Luanda.\n\nA visita inclui o interior da Fortaleza com o seu Museu das Forças Armadas, a Catedral de Luanda, o Museu Nacional de Arqueologia e a Assembleia Nacional. O guia especializado narra a história de Luanda desde a fundação portuguesa até à independência em 1975.\n\nTermina com uma caminhada pela Avenida Marginal, com vista panorâmica para a Baía de Luanda.",
                'city' => 'Luanda',
                'province' => 'Luanda',
                'location' => 'Fortaleza de São Miguel, Cidade Alta, Luanda',
                'price' => 12000.00,
                'duration_days' => 1,
                'max_participants' => 20,
                'available_spots' => 20,
                'category' => 'historico',
                'difficulty' => 'facil',
                'is_active' => true,
                'is_featured' => false,
                'highlights' => ['Fortaleza de São Miguel (1576)', 'Centro histórico colonial', 'Catedral de Luanda', 'Museu das Forças Armadas'],
                'includes' => ['Entradas em todos os museus', 'Guia histórico especializado', 'Mapa histórico de Luanda'],
                'excludes' => ['Transporte próprio', 'Refeições', 'Fotografia profissional'],
            ],
            [
                'name' => 'Praia do Lobito e Lagoa do Restelo',
                'short_description' => 'Um dia relaxante entre as famosas praias do Lobito e a serena Lagoa do Restelo, um dos segredos mais bem guardados de Benguela.',
                'description' => "O Lobito é a segunda maior cidade de Angola e possui algumas das praias mais belas do país. A Lagoa do Restelo, a poucos quilómetros da cidade, é uma lagoa costeira de águas tranquilas rodeada de fauna e flora endémica.\n\nEste tour de 1 dia inclui visita às principais praias do Lobito, com tempo livre para nadar e relaxar, seguido de passeio de barco pela Lagoa do Restelo onde é possível observar flamingos e outras aves aquáticas.\n\nÀ tarde, visita ao mercado de artesanato local e degustação de bebidas e petiscos típicos num quiosque com vista para o mar.",
                'city' => 'Lobito',
                'province' => 'Benguela',
                'location' => 'Praia do Lobito, Benguela',
                'price' => 38000.00,
                'duration_days' => 1,
                'max_participants' => 15,
                'available_spots' => 13,
                'category' => 'natureza',
                'difficulty' => 'facil',
                'is_active' => true,
                'is_featured' => false,
                'highlights' => ['Praias com águas cristalinas', 'Lagoa do Restelo com flamingos', 'Passeio de barco', 'Artesanato local'],
                'includes' => ['Transporte local', 'Passeio de barco', 'Snacks e bebidas', 'Guia local'],
                'excludes' => ['Refeição principal', 'Compras pessoais', 'Gorjetas'],
            ],
            [
                'name' => 'Namibe - Deserto e Planície Costeira',
                'short_description' => 'Aventura de 3 dias pelo deserto do Namibe, com dunas vermelhas, fauna silvestre única e o litoral selvagem de Angola.',
                'description' => "O Deserto do Namibe (Moçâmedes) é um dos desertos costeiros mais antigos do mundo, com mais de 55 milhões de anos. Esta aventura de 3 dias é para explorar este ecossistema único com a orientação de guias especializados locais.\n\nDia 1: Chegada ao Namibe, visita ao Museu Regional, entrada nas dunas próximas da cidade e pôr-do-sol no litoral selvagem.\n\nDia 2: Excursão ao Parque Nacional do Iona, o mais antigo parque de Angola, com possibilidade de avistamento de leões, girafas-de-angola, oryx e a magnífica flora do deserto, incluindo as Welwitschia.\n\nDia 3: Visita à Figueira Brava (fico endémico), passeio de quadriciclo pelas dunas e voo de regresso a Luanda.",
                'city' => 'Namibe',
                'province' => 'Namibe',
                'location' => 'Aeroporto do Namibe',
                'price' => 180000.00,
                'duration_days' => 3,
                'max_participants' => 8,
                'available_spots' => 6,
                'category' => 'aventura',
                'difficulty' => 'dificil',
                'is_active' => true,
                'is_featured' => true,
                'highlights' => ['Deserto com 55 milhões de anos', 'Parque Nacional do Iona', 'Girafas-de-Angola', 'Passeio de quadriciclo nas dunas'],
                'includes' => ['Voo Luanda-Namibe-Luanda', 'Alojamento 2 noites', 'Todas as refeições', 'Guia desertor especializado', 'Quadriciclo 1 hora'],
                'excludes' => ['Bebidas alcoólicas', 'Equipamento pessoal', 'Gorjetas', 'Seguro de viagem'],
            ],
        ];

        foreach ($tours as $tour) {
            Tour::create(array_merge($tour, [
                'slug' => \Illuminate\Support\Str::slug($tour['name']),
            ]));
        }
    }
}
